CREATE TABLE Room (
	roomID		VARCHAR(10)	NOT NULL,
	size		INT		NOT NULL,
	PRIMARY KEY (roomID)
);


CREATE TABLE Entry (
	entryID		BIGINT		NOT NULL,
	startTime	TIMESTAMP	NOT NULL,
	endTime		TIMESTAMP	NOT NULL,
	location	VARCHAR(20),
	description	VARCHAR(100)	NOT NULL,
	isActive	BOOLEAN		DEFAULT TRUE,
	roomID	VARCHAR(10),
	PRIMARY KEY (entryID),
	FOREIGN KEY (roomID) REFERENCES Room (roomID)
		ON UPDATE CASCADE	
);

CREATE TABLE User (
	username	VARCHAR(10)	NOT NULL,
	name		VARCHAR(30)	NOT NULL,
	password	VARCHAR(20)	NOT NULL,
	salt		VARCHAR(30)	NOT NULL,
	email		VARCHAR(50)	NOT NULL,
	PRIMARY KEY (username)
);

CREATE TABLE Invitation (
	isGoing		BOOLEAN		DEFAULT NULL,
	isShowing	BOOLEAN		DEFAULT TRUE,
	username	VARCHAR(10)	NOT NULL,
	entryID		BIGINT		NOT NULL,
	PRIMARY KEY (username, entryID),
	FOREIGN KEY (username) REFERENCES User (username)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (entryID) REFERENCES Entry (entryID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Notification (
	description	VARCHAR(100)	NOT NULL,
	isOpened	BOOLEAN		DEFAULT FALSE,
	time		TIMESTAMP	NOT NULL,
	username	VARCHAR(10)	NOT NULL,
	entryID		BIGINT		NOT NULL,
	PRIMARY KEY(username, entryID),
	FOREIGN KEY(username) REFERENCES User(username)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (entryID) REFERENCES Entry(entryID)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IsAdmin (
	entryID		BIGINT		NOT NULL,
	username	VARCHAR(10)	NOT NULL,
	PRIMARY KEY (entryID, username),
	FOREIGN KEY (entryID) REFERENCES Entry(entryID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (username) REFERENCES User(username)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Gruppe (
	groupID	VARCHAR(10)	NOT NULL,
	PRIMARY KEY (groupID)
);

CREATE TABLE MemberOf (
	groupID		VARCHAR(10)	NOT NULL,
	username	VARCHAR(10)	NOT NULL,
	PRIMARY KEY (groupID, username),
	FOREIGN KEY (groupID) REFERENCES Gruppe(groupID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (username) REFERENCES USER(username)
		ON UPDATE CASCADE ON DELETE CASCADE
);
	
	
	
